# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = monospace

##############
### COLORS ###
##############

$root_background_color = 141414
$primary_border_color = 282828 

general {
    hide_cursor = false
    fail_timeout = 1500
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldColors, 1, 2, easeInOutCubic
    animation = inputFieldDots, 1, 1, linear
}

background {
	color = rgb($root_background_color)
}

input-field {
    monitor =
    size = 180, 28 
    outline_thickness = 2
    inner_color = rgb(262626)

    outer_color = rgb(262626)
    check_color = rgb(4D4D4D)
    fail_color = rgb(EF5350)

    font_color = rgb(666666)
    fade_on_empty = true
    rounding = -1 

    font_family = $font
    placeholder_text =
    fail_text = 
    # placeholder_text = <span font_size="12">Enter Password</span>
    # fail_text = Incorrect Password

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.25
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 200
    halign = center
    valign = bottom
}

# time
label {
    monitor =

    text = cmd[update:1000] echo "$(date +"%T")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 10
    font_family = $font

    position = 0, -640
    halign = center
    valign = top
}

# date
label {
    monitor =

    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 10
    font_family = $font

    position = 0, -660
    halign = center
    valign = top
}
