set -g status-style bg="#262626",fg="#fefefe"

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded!"

set -g mouse on

bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"

set -g status-left "#[bg=#E1BEE7,fg=#1a1a1a] #S #[default] "
set -g status-right ""
set -g status-justify left 

set -g set-clipboard on

set-window-option -g window-status-separator ''
set -g window-status-format '#[fg=#707070][#I] #W '
set -g window-status-current-format '#[fg=#E1BEE7][#I] #W '

set -g pane-active-border-style fg='#E1BEE7'
set -g pane-border-style fg='#707070'
